Books/urls.py
from django.urls import path
from .views import BookListView, return_book, borrow_book
app_name = 'Books'
urlpatterns = [
    path('',BookListView.as_view() , name='home'),
    path('return/<str:slug>', return_book, name='return'),
    path('borrow/<str:slug>', borrow_book, name='borrow'),

]

MyLibrary/urls.py
from Books.views import author_book_list, category_book_list
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import ContactUs
urlpatterns = [
    path('contact/', ContactUs.as_view(), name='contact'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include('Books.urls', namespace='Books')),
    path('dashboard_admin/', include('Admin.urls', namespace='Admin')),
    path('blog/', include('blog.urls', namespace='Blog')),
    path('category/<str:slug>', category_book_list, name='category_book_list'),
    path('author/<str:slug>', author_book_list, name='author_book_list'),
    path('admin/', admin.site.urls),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import UpdateData, sign_up
from django.contrib.auth.views import LogoutView
# from django.contrib.auth.views import LogoutView
app_name = "accounts"
urlpatterns = [
    # path('signup/' , SignUp.as_view() , name="signup"),  #I don't know why this way dos't work i will try to do that later on my own
    path('signup/' , sign_up , name="signup"),
    path('profile/', UpdateData.as_view(), name="profile"),
    path('logoutt/', LogoutView.as_view(template_name='registration/logout.html'), name='logoutt'),
]

blog/urls.py
from blog.views import BlogView
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', BlogView.as_view() ,name='blog')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from PIL import Image 
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_image = models.ImageField(upload_to="profile_pics",null=True, blank=True, default='default.jpg')
    phone_number = PhoneNumberField(region='EG',blank=True,null=True)
    gender = models.CharField(max_length=2,choices=(('M' , 'Male') , ('F' , 'Female')))
    birthday = models.DateField(null=1,blank=1)
    address = models.CharField(max_length=300, null=1, blank=1)
    
    def __str__(self):
        return f'{self.user.username} Profile'

    # def save(self, *args, **kwargs):
    #     super(Profile, self).save(*args, **kwargs)
    #     if self.profile_image != None:
    #         img = Image.open(self.profile_image.path)
    #         if img.height > 300 or img.width > 300:
    #             new_size = (300, 300)
    #             img.thumbnail(new_size)
    #             img.save(self.profile_image.path)
    def custom_save(self, *args, **kwargs):
        self.user = kwargs.get('user')
        self.save()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile
import phonenumbers
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]


class ProfileRegisterForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image', 'phone_number', 'gender', 'birthday', 'address']
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image', 'phone_number', 'gender', 'birthday', 'address']
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

accounts/views.py
from Books.models import Category
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import redirect, render 
from .forms import UserRegisterForm , ProfileRegisterForm , UserUpdateForm , ProfileUpdateForm
from django.views import View
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
# Create your views here.
class SignUp(View):

    def get (self, request, *args, **kwargs):
        user_form = UserRegisterForm()
        profile_form = ProfileRegisterForm()
        context = {'user_form':user_form, 'profile_form':profile_form}
        return render(request, "register.html", context)
    
    def post (self, request, *args, **kwargs):
        user_form = UserRegisterForm(request.POST)
        profile_form = ProfileRegisterForm(request.POST , request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            user = authenticate(username = user_form.cleaned_data.get('username') , password = user_form.cleaned_data.get('password1'))
            profile_form.custom_save(user=user)
        return redirect(reverse('accounts:profile'))

class UpdateData(View):
    def post(self, request, *args, **kwargs):
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.user_profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile Data has been updated successfully!')
            return redirect(reverse('accounts:profile'))
        else:
            messages.error(request, f'Invalid Date, Please Try Again!')
            return redirect(reverse('accounts:profile'))
    def get (self, request, *args, **kwargs):
        user_form = UserUpdateForm()
        profile_form = ProfileUpdateForm()
        profile = request.user.user_profile
        books = request.user.user_books.all()
        categories = Category.objects.all()
        context = {'user_form':user_form, 'profile_form':profile_form, 'profile':profile, 'Books':books, 'Categories':categories}
        return render(request, 'profile.html', context)


class ContactUs(View):
    def post (self, request, *args, **kwargs):
        email = request.POST['email']
        subject = request.POST['subject']
        msg = request.POST['message']
        send_mail (
            subject,
            msg,
            settings.EMAIL_HOST_USER,
            [email],
        )
        return redirect(reverse('contact'))
    def get (self, request, *args, **kwargs):
        categories = Category.objects.all()
        return render(request, 'contact_us.html',{'Categories':categories})

def sign_up(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('accounts:profile'))
            
    else:
        form = UserRegisterForm()
    return render(request, 'register.html' , {'form':form})

accounts/templates/base_generic.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Online Library</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'accounts/img/favicon.ico' %} " type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'accounts/img/icon.png' %}">

    <!-- ************************* CSS Files ************************* -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.css' %}">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'accounts/css/vendor.css' %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static 'accounts/css/main.css' %}">
</head>



<body>


    <!-- ************************* Add NavrBar ************************* -->

    
    <!-- Preloader Start -->
    <div class="ft-preloader active">
        <div class="ft-preloader-inner h-100 d-flex align-items-center justify-content-center">
            <div class="ft-child ft-bounce1"></div>
            <div class="ft-child ft-bounce2"></div>
            <div class="ft-child ft-bounce3"></div>
        </div>
    </div>
    <!-- Preloader End -->

        <!-- Breadcrumb area Start -->
        <section class="page-title-area bg-color" data-bg-color="#f4f4f4">
            <div class="container">
                <div class="row">
                    <div class="col-8 text-center mx-auto" style="display:block;width:100%%;">
                        <h1 class="page-title">
                            {% block pagetitle %}
                            {% endblock pagetitle %}
                        </h1>
                        <ul class="breadcrumb">

                            <!-- Link Home Hereee -->
                            <li><a href="{% url 'Books:home' %}">Home</a></li>
                            <li class="current">
                                <span>                            
                                    {% block title %}
                                    {% endblock title %}
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <!-- Breadcrumb area End -->

        <!-- Main Content Wrapper Start -->
        <div class="main-content-wrapper">
            <div class="page-content-inner pt--75 pb--80">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 mx-auto">
                            {% block content %}
                            {% endblock content %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->

        <!-- ************************* Add Footer ************************* -->

</body>

    <!-- Main Wrapper End -->

    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="{%static 'accounts/js/vendor.js'%}"></script>

    <!-- Main JS -->
    <script src="{% static 'accounts/js/main.js' %}"></script>
    <!--js-->
    <script>
        e = document.getElementsByTagName('small');
        for(var i = 0 ; i < e.length; i++){
            e[i].innerText = " ";
        }
        e1 = document.getElementsByClassName("alert")[0];
        document.getElementsByClassName("close")[0].addEventListener("click" , () =>{
                e1.style.display = 'none';
            });

    </script>
</html>

accounts/templates/contact_us.html
{% extends "Books/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block slider %}
        <section class="page-title-area bg-color" data-bg-color="#f4f4f4">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <h1 class="page-title">Send Us An Email</h1>
                        <ul class="breadcrumb">
                            <li><a href="/home">Home</a></li>
                            <li class="current"><span>Contact Us</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
{% endblock  %}
{% block part1 %}
    <div class="contact-clean">
        <form method="post">
            {% csrf_token %}
            <div class="form-group mt-2"><input class="form-control" type="email" name="email" placeholder="Email"></div>
            <div class="form-group mt-2"><input class="form-control" type="text" name="subject" placeholder="Subject"></div>
            <div class="form-group mt-2"><textarea class="form-control" name="message" placeholder="Message" rows="14"></textarea></div>
            <div class="form-group mt-2"><button class="btn btn-primary mx-auto" style="display:block;" type="submit">send </button></div>
        </form>
    </div>
{% endblock %}

accounts/templates/register.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block pagetitle %}Register{% endblock pagetitle %}
{% block content %}
    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% comment %} {{ user_form|crispy }}
        {{ profile_form|crispy }} {% endcomment %}
        {{ form|crispy }}  
        <input style="display:block;" type="submit" class="btn btn-primary  mt-3 mb-3 mx-auto" value="Register">
    </form>
{% endblock content %}
{% block title %}
    Register
{% endblock title %}